
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ping:1})'"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge